apiVersion: v1
kind: Pod
metadata:
  name: hadoop-slave01
  namespace: hadoop
  labels:
    app: hadoop-slave01
spec:
  hostname: hadoop-slave01
  containers:
  - name: hadoop
    image: apache/hadoop:3
    command:
    - /bin/bash
    - -c
    - |
      export HADOOP_HOME=/opt/hadoop
      export PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin

      cp /config/core-site.xml $HADOOP_HOME/etc/hadoop/core-site.xml
      cp /config/hdfs-site.xml $HADOOP_HOME/etc/hadoop/hdfs-site.xml
      cp /config/yarn-site.xml $HADOOP_HOME/etc/hadoop/yarn-site.xml

      mkdir -p /tmp/hadoopdata/hdfs/datanode

      $HADOOP_HOME/bin/hdfs --daemon start datanode
      sleep 2
      $HADOOP_HOME/bin/yarn --daemon start nodemanager

      echo ">>> Slave01 started!"
      tail -f /dev/null
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
    volumeMounts:
    - name: config
      mountPath: /config
  volumes:
  - name: config
    configMap:
      name: hadoop-config
---
apiVersion: v1
kind: Pod
metadata:
  name: hadoop-slave02
  namespace: hadoop
  labels:
    app: hadoop-slave02
spec:
  hostname: hadoop-slave02
  containers:
  - name: hadoop
    image: apache/hadoop:3
    command:
    - /bin/bash
    - -c
    - |
      export HADOOP_HOME=/opt/hadoop
      export PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin

      cp /config/core-site.xml $HADOOP_HOME/etc/hadoop/core-site.xml
      cp /config/hdfs-site.xml $HADOOP_HOME/etc/hadoop/hdfs-site.xml
      cp /config/yarn-site.xml $HADOOP_HOME/etc/hadoop/yarn-site.xml

      mkdir -p /tmp/hadoopdata/hdfs/datanode

      $HADOOP_HOME/bin/hdfs --daemon start datanode
      sleep 2
      $HADOOP_HOME/bin/yarn --daemon start nodemanager

      echo ">>> Slave02 started!"
      tail -f /dev/null
#    resources:
#      requests:
#        memory: "512Mi"
#        cpu: "500m"
#      limits:
#        memory: "1Gi"
#        cpu: "1000m"
    volumeMounts:
    - name: config
      mountPath: /config
  volumes:
  - name: config
    configMap:
      name: hadoop-config
#EOF